name: hive_flutter_plus
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 2.0.0-dev.1
homepage: https://github.com/lamnhan066/hive/tree/main/hive_flutter
documentation: https://docs.hivedb.dev/

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  cryptography: ^2.0.5
  hive_plus: ^3.0.0-dev.1
  path_provider: ^2.0.10
  path: ^1.8.1

dev_dependencies:
  test: ^1.25.2
  lints: ">=1.0.0"
  mockito: ^5.2.0
  build_runner: ^2.1.11
