name: hive_plus
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 3.0.0-dev.2
homepage: https://github.com/lamnhan066/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.3.0
  crypto: ^3.0.0
  web: ^1.0.0

dev_dependencies:
  test: ^1.17.12
  mocktail: ^1.0.4
  lints: ^4.0.0
  path: ^1.7.0
  pointycastle: ^3.0.1
  build_runner: ^2.1.2
